# 站点基本信息
title: "张梦军的博客"   # 你的博客标题
name: "shenzhenren"
description: "这是我的个人博客，记录工作和学习"
url: "https://shenzhenren.github.io"  # 你的 GitHub Pages 网址
baseurl: ""  # 这里保持空值，不要加 /

# 主题设置
remote_theme: "mmistakes/minimal-mistakes"  # 启用 Minimal Mistakes 主题
minimal_mistakes_skin: "default"  # 主题风格，可以改成 "dark" 试试黑色主题

# 站点作者信息
author:
  name: "shenzhenren"
  bio: "热爱工作，记录学习"
  location: "深圳"
  email: "547990706@qq.com"  # 可以改成你的真实邮箱
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/shenzhenren"

# 文章相关设置
permalink: /:categories/:title/  # 文章 URL 结构
paginate: 5  # 主页每页显示 5 篇文章
paginate_path: "/page:num/"

# 开启 Jekyll 插件
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-include-cache
# 禁用 GitHub Pages 的默认页脚
footer:
  enabled: false
