theme: jekyll-theme-cayman  # 你可以换成你的主题，如 jekyll-theme-minimal

footer:
  custom_text: ""  # 这行代码禁用默认页脚提示
theme: jekyll-theme-cayman  # 你可以换成你的主题
show_downloads: false  # 可能有助于减少 GitHub Pages 相关的内容

footer:
  custom_text: ""  # 清空页脚内容
